---

# This file overrides the main docker-compose.yml

services:

  hass:
    environment:
      - SWIPE_NAVIGATION_JS_URL=http://builder:3000/swipe-navigation.js


  tester:
    build:
      context: ./docker/builder/

    environment:
      - CI
      - HOMEASSISTANT_URL=http://hass:8123
      - SWIPE_NAVIGATION_JS_URL=http://builder:3000/swipe-navigation.js

    volumes:
      - .:/project

      # Keep node_modules only inside a volume (for decluttering and performance)
      - nodemodules_tester:/project/node_modules

      # Sync time with host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    working_dir: /project

    depends_on:
      - builder
      - hass

    command: ./scripts/run-playwright.sh


volumes:
  nodemodules_tester:
