# This file overrides the main docker-compose.yml

services:
  builder:
    environment:
      - HOMEASSISTANT_URL=http://hass:8123

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  hass:
    profiles:
      - do_not_start_by_default
